const laptopList = [
    {
        id: 3654,
        name: 'Hotel Pinaka',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Apartments',
        price: 1200,
        image: './Assets/Apartments1.webp',
    },
    {
        id: 3654,
        name: 'Aashiyana Homes',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Apartments',
        price: 2200,
        image: './Assets/Apartments2.webp',
    },
    {
        id: 3654,
        name: 'Hotel Agoura',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Apartments',
        price: 1400,
        image: './Assets/Apartments3.webp',
    },
    {
        id: 3654,
        name: 'Hotel D SilverLeaf',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Apartments',
        price: 4000,
        image: './Assets/Apartments4.webp',
    },
    {
        id: 3654,
        name: 'Hotel Sarvin',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Apartments',
        price: 5000,
        image: './Assets/Apartments5.webp',
    },

    {
        id: 3654,
        name: 'Hyatt Regency',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Hotel',
        price: 6000,
        image: './Assets/hotel1.webp',
    },

    {
        id: 3654,
        name: 'Novotel Lucknow',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Hotel',
        price: 6000,
        image: './Assets/hotel2.webp',
    },

    {
        id: 3654,
        name: 'Hyatt Regency',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Hotel',
        price: 6000,
        image: './Assets/hotel3.webp',
    },

    {
        id: 3654,
        name: 'Hyatt Regency',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Hotel',
        price: 6000,
        image: './Assets/hotel4.webp',
    },
    {
        id: 3654,
        name: 'Hotel Pinaka',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Hotel',
        price: 7100,
        image: './Assets/hotel5.webp',
    },

    {
        id: 3654,
        name: 'Hotel Aarya',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Guest_Houses',
        price: 1800,
        image: './Assets/Guest_Houses1.webp',
    },
    {
        id: 3654,
        name: 'Hotel Aarya',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Guest_Houses',
        price: 1800,
        image: './Assets/Guest_Houses2.webp',
    },
    {
        id: 3654,
        name: 'Hotel Aarya',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Guest_Houses',
        price: 1800,
        image: './Assets/Guest_Houses3.webp',
    },
    {
        id: 3654,
        name: 'Hotel Aarya',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Guest_Houses',
        price: 1800,
        image: './Assets/Guest_Houses4.webp',
    },

    {
        id: 3654,
        name: 'Hotel Aarya',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Hostels',
        price: 1800,
        image: './Assets/Hostels.jpeg',
    },
    {
        id: 3654,
        name: 'Hotel Aarya',
        location: 'Lucknow',
        address: 'Gomti Nagar',
        type: 'Resorts',
        price: 1800,
        image: './Assets/Resorts.jpeg',
    },

];

export default laptopList;